# MIT License
#
# Copyright (c) 2021 Johan Ludde Wessén
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

from problem_instance import Problem


class ProblemPrinter:
    
    def __init__(self, fixture_order_raw, duration_rnd_seed, **kwargs):




        self.p = Problem(fixture_order_raw = fixture_order_raw, **kwargs)

        self.fixture_order_raw = fixture_order_raw

        self.no_grip = None
        self.no_suction = None
        self.duration_rnd_seed = duration_rnd_seed


    def GetFixtureOrderString(self):
        s = ""
        current = ""
        for i in range(len(self.fixture_order_raw)):
            if self.fixture_order_raw[i] == 0:
                current = "G"
            elif self.fixture_order_raw[i] == 1:
                current = "S"

            elif self.fixture_order_raw[i] == -1:
                current = "_"
            else:
                current = "ERROR"

            s = s + current

        return s

    def GetNoComp(self):
        return self.p.no_grip + self.p.no_suction

    def FilePrint(self, file_name_prefix):

        """
            Printing File Header
        """

        setup_file_name = file_name_prefix + str(self.GetNoComp()) + "_" + self.GetFixtureOrderString() + ".dzn"
        file1 = open(setup_file_name,"w")

        file1.write("%-----------------------------------------------------------------------------%\n")
        file1.write("% Dual Arm Multi Capacity Multi Tool Scheduling / Routing\n")
        file1.write("% Assembly Configuration\n")
        file1.write("% Auto Generated by python script, authored by Johan Ludde Wessen \n")
        file1.write("%-----------------------------------------------------------------------------%\n\n\n")

        """
            Printing durations
        """
        self.p.RandomizeTaskDurations(self.duration_rnd_seed)

        file1.write("task_durations = ")
        file1.write(self.p.GetDurationsOfTasksString(str_offset=len("task_durations = ")+1))
        file1.write('\n\n\n')

        """
            Printing task sets
        """

        file1.write("TRAY_TASKS = " + self.p.TrayTasksToString() + ";\n")
        file1.write("CAMERA_TASKS = " + self.p.CameraTasksToString()  + ";\n")
        file1.write("OUTPUT_TASKS = " + self.p.OutputTasksToString()  + ";\n")

        file1.write('\n\n')

        file1.write("empty_gripper_tasks = " + self.p.PressTasksToString()  + ";\n")

        file1.write('\n\n')

        """
            Printing Tool Pick and Place- orders
        """
        # TODO: last row does not seem to have press - which it does no, since it is output
        # However, we assume it does!
        # Fix!
        file1.write("gripper_pick_tasks_orders = " + self.p.GetPickTaskOrderString(0) + ";\n\n")
        file1.write("suction_pick_tasks_orders = " + self.p.GetPickTaskOrderString(1) + ";\n\n")

        file1.write("fixture_task_orders = " + self.p.GetFixtureTaskOrderString() + ";\n\n")


        file1.close()

        return setup_file_name
